# Generated by Django 3.2.9 on 2021-12-02 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sedzia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Turniej',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=45)),
                ('adres', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Uczestnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
                ('nr_tel', models.IntegerField()),
                ('nr_email', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Rozgrywka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wynik_ucz1', models.IntegerField()),
                ('wynik_ucz2', models.IntegerField()),
                ('id_sedzia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turniej.sedzia')),
                ('id_turniej', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turniej.turniej')),
                ('id_ucz1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id1', to='turniej.uczestnik')),
                ('id_ucz2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id2', to='turniej.uczestnik')),
            ],
        ),
    ]
