# Generated by Django 3.2.9 on 2021-12-02 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turniej', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rozgrywka',
            old_name='id_sedzia',
            new_name='sedzia',
        ),
        migrations.RenameField(
            model_name='rozgrywka',
            old_name='id_ucz1',
            new_name='ucz1',
        ),
        migrations.RenameField(
            model_name='rozgrywka',
            old_name='id_ucz2',
            new_name='ucz2',
        ),
    ]
