# Generated by Django 3.2.9 on 2021-12-02 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turniej', '0002_auto_20211202_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rozgrywka',
            old_name='id_turniej',
            new_name='turniej',
        ),
    ]
