# Generated by Django 3.2.9 on 2022-01-24 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turniej', '0003_rename_id_turniej_rozgrywka_turniej'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rozgrywka',
            name='turniej',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mecze', to='turniej.turniej'),
        ),
    ]
