# Generated by Django 3.2.9 on 2022-01-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turniej', '0004_alter_rozgrywka_turniej'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turniej',
            old_name='adres',
            new_name='miasto',
        ),
        migrations.AddField(
            model_name='turniej',
            name='data',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='turniej',
            name='nr_budynku',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='turniej',
            name='ulica',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='uczestnik',
            name='wiek',
            field=models.IntegerField(null=True),
        ),
    ]
