# Generated by Django 3.2.9 on 2022-01-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turniej', '0005_auto_20220125_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turniej',
            name='nr_budynku',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
