# Generated by Django 3.2.9 on 2022-01-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turniej', '0006_alter_turniej_nr_budynku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turniej',
            name='data',
            field=models.DateField(null=True),
        ),
    ]
