# Generated by Django 3.2.9 on 2022-01-27 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turniej', '0007_auto_20220127_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='uczestnik',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uczestnik', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rozgrywka',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rozgrywka', to=settings.AUTH_USER_MODEL),
        ),
    ]
